server:
  port: 8888

spring:
  application:
    name: jokes demo

  h2:
    console:
      enabled: true
      path: /h2-console
    database-platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  datasource:
      driver-class-name: org.h2.Driver
      username: sa
      password:
      url: jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# ----------------------------------------
# Swagger Configurations
# ----------------------------------------
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /v0/list-all-api.html
    tagsSorter: alpha
    enabled: true
swagger:
  server:
    url: http://localhost:8888