server:
  port: 8888

spring:
  application:
    name: jokes demo

# ----------------------------------------
# Swagger Configurations
# ----------------------------------------
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /v0/list-all-api.html
    tagsSorter: alpha
    enabled: true
swagger:
  server:
    url: http://localhost:8888