server:
  port: 8888

spring:
  application:
    name: jokes demo

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

# ----------------------------------------
# Swagger Configurations
# ----------------------------------------
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /v0/list-all-api.html
    tagsSorter: alpha
    enabled: true
swagger:
  server:
    url: http://localhost:8888